research_task:
  description: >
    Perform a complete travel research taking into account the following indications: 
    
    {num_travelers} people named {names} aged {ages} are Wayners from {origin} travelling to 
    {destination} between {start_date} arriving at {flight_outward_arrival_time} 
    and {end_date} departing at {flight_return_departure_time} from {destination}'s airport. 
    The travellers are staying at {hotel_name}, which is already booked for {names}. 
    Is breakfast included? {breakfast_included}. The flights are also booked:
    {flight_data}. 
    Only hotel and flights are booked, any other activity is not booked yet.
  expected_output: >
    Comprehensive and structured research information so the director of itinerary development can perform a sensible, complete, personalized and date-specific itinerary. Includes enough activities of each category for the trip duration.

itinerary_task:
  description: >
    Perform a complete travel itinerary taking into account the following indications: 
    
    {num_travelers} people named {names} aged {ages} are Wayners from {origin} travelling to 
    {destination} between {start_date} arriving at {flight_outward_arrival_time} 
    and {end_date} departing at {flight_return_departure_time} from {destination}'s airport. 
    The travellers are staying at {hotel_name}, which is already booked for {names}. 
    Is breakfast included? {breakfast_included}. The flights are also booked:
    {flight_data}. 
    Only hotel and flights are booked, any other activity is not booked yet.
  expected_output: >
    Personalized and comprehensive yet concise travel itinerary taking into account the research agent's information, with all useful details and including flight and hotel information.

itinerary_geo_organization:
  description: >
    Optimize the itinerary in geographical terms for a logical distribution of activities and include public transportation options with detail or walking distances between activities. Take into account the following indications: 
    
    {num_travelers} people named {names} aged {ages} are Wayners from {origin} travelling to 
    {destination} between {start_date} arriving at {flight_outward_arrival_time} 
    and {end_date} departing at {flight_return_departure_time} from {destination}'s airport. 
    The travellers are staying at {hotel_name}, which is already booked for {names}. 
    Is breakfast included? {breakfast_included}. The flights are also booked:
    {flight_data}. 
    Only hotel and flights are booked, any other activity is not booked yet.
  expected_output: >
    Fully developed, complete, detailed, and geographically optimized itinerary with distances and transportation options (including times and prices when appropriate) between activities, including ONLY EITHER PUBLIC TRANSPORTATION OR WALKING COMMUTES, NEVER INCLUDING TAXI OR PRIVATE SHUTTLES.

link_adding_task:
  description: >
    Enhance the given COMPLETE itinerary with relevant links for ALL THE TRAVEL DAYS, links to ALL activities, restaurants, accommodations (...) mentioned in the itinerary. 
    For activities, tours (...) include ONLY CIVITATIS links and include '&aid=2264' at the end of each link. 
    DO YOUR BEST TO INCLUDE AT LEAST ONE CIVITATIS AFFILIATE LINK, SINCE YOUR VARIABLE SALARY DEPENDS ON IT.
  expected_output: >
    An enhanced FULL, COMPLETE itinerary for ALL THE TRAVEL DAYS with links in every single day of the itinerary for each relevant activity, transportation option, restaurant suggestion (...).

itinerary_translation_and_writing:
  description: >
    Develop and translate a message in WhatsApp format including all relevant information and the complete, day-by-day itinerary prepared to be sent to the user. Consider the following indications:
    
    {num_travelers} people named {names} aged {ages} are Wayners from {origin} travelling to 
    {destination} between {start_date} arriving at {flight_outward_arrival_time} 
    and {end_date} departing at {flight_return_departure_time} from {destination}'s airport. 
    The travellers are staying at {hotel_name}, which is already booked for {names}. 
    Is breakfast included? {breakfast_included}. The flights are also booked:
    {flight_data}. 
    Only hotel and flights are booked, any other activity is not booked yet.
  expected_output: >
    An informal, playful and helpful Whatsapp text-message in text format (NOT MARKDOWN) READY TO BE SENT DIRECTLY TO {names} (wayners) in their country's national language. MAKE SURE IT IS IN {origin}'s country's national language.
    It must include the FULL COMPLETE DETAILED RECOMMENDED ITINERARY DAY BY DAY WITH ALL THE DAYS ACTIVITIES AND TRANSPORT OPTIONS developed up to now (including all links and useful data points) addressing the travellers as "Wayners".
    Make sure you frame it as a RECOMMENDED itinerary and consider that THE FULL OUTPUT WILL BE RECEIVED BY {names}, so JUST PROVIDE THE TEXT TO BE SENT TO THE TRAVELLERS. NEVER ASSUME ACTIVITES (EXCEPT HOTELS AND FLIGHTS) ARE ALREADY BOOKED, THEY ARE JUST RECOMMENDATIONS. Sign as Olga from Waynabox.
    It must have the FULL COMPLETE following structure and the full text must be in {origin}'s country national official language:
    - Greeting and presentation of the recommended itinerary.
    - Hotel Information (stars, location, reviews...).
    - Flight Information (with links to flightradar24 with the flight code).
    - Specific weather forecast day by day.
    - The complete, previous itinerary. Maintain ALL THE DETAILS.
    - Fun facts and top tips, such as what to book in advance.
    - Olga Informal Signature.
