research_task:
  description: >
    Perform a complete travel research. When researching, you MUST PROFILE THE TRAVELLERS AND GUESS THEIR PROBABLE INTERESTS: 
    
    {num_travelers} people named {names} aged {ages} are Wayners from {origin} travelling to 
    {destination} between {start_date} arriving at {flight_outward_arrival_time} 
    and {end_date} departing at {flight_return_departure_time} from {destination}'s airport. 
    The travellers are staying at {hotel_name}, which is already booked for {names}. 
    Is breakfast included? {breakfast_included}. The flights are also booked:
    {flight_data}. 
    Only hotel and flights are booked, any other activity is not booked yet.
    DO NOT INVENT ANY INFORMATION.
    DO NOT FORGET TO RESEARCH THE WEATHER THROUGH ACCUWEATHER.
  expected_output: >
    Comprehensive and structured research information so the director of itinerary development can perform a sensible, complete, personalized and date-specific itinerary. Includes enough activities of each category for the trip duration.

itinerary_task:
  description: >
    Perform a complete travel itinerary taking into account the following indications:
    
    {num_travelers} people named {names} aged {ages} are Wayners from {origin} travelling to 
    {destination} between {start_date} arriving at {flight_outward_arrival_time} 
    and {end_date} departing at {flight_return_departure_time} from {destination}'s airport. 
    The travellers are staying at {hotel_name}, which is already booked for {names}. 
    Is breakfast included in the hotel? {breakfast_included}. The flights are also booked:
    {flight_data}. 
    Only hotel and flights are booked, any other activity is not booked yet.
    PRIORITIZE THE TOP 3 ACTIVITIES OFFERED BY CIVITATIS WHERE POSSIBLE, UNLESS WEATHER, TRAVELLER DEMOGRAPHICS.
    FOR OTHER ACTIVITIES, DO NOT MENTION CIVITATIS.
    AVOID DUPLICATING ACTIVITIES OR SIMILAR ONES (one or more similar words).
    DO NOT INCLUDE LINKS.
    DO NOT INVENT ANY INFORMATION.
    YOUR MUST MAKE LUNCH AND DINNER TIMES ADEQUATE FOR THE TRAVELLERS' DEPARTURE CITY CULTURE (for instance, those departing from Spanish have lunch at 14 and dinner at 21).
    IMPORTANT: EVERY ELEMENT OF THE ITINERARY MUST BE JUSTIFIED WITH THE WEATHER FORECAST AND TRAVELLERS' AGES.
    ASSUME THAT HOTEL CHECK-IN TIME IS 15:00 FOR THE ITINERARY. HOWEVER, LUGGAGE MAY BE LEFT IN THE HOTEL BEFORE CHECK-IN TIME.
    INCLUDE PRICE ESTIMATES OF ALL THE RESTAURANTS AND TRANSPORTATION OPTIONS.
  expected_output: >
    Personalized and comprehensive travel itinerary using the information collected by the research agent, prioritizing Civitatis activities, and ensuring no duplicate or similar activities are included.
    It must contain the following structure:
    - Greeting and presentation of the recommended itinerary.
    - Hotel Information (stars, location, reviews...).
    - Flight Information.
    - Specific weather forecast day by day.
    - Extensive, complete itinerary with prioritized Civitatis activities.
    - Fun facts and top tips, such as what to book in advance.
    - Olga Informal Signature.


itinerary_geo_organization:
  description: >
    Optimize the itinerary in geographical terms for a logical distribution of activities and include public transportation options with detail or walking distances between ALL AND EACH OF THE PLACES. Take into account the following indications: 
    
    {num_travelers} people named {names} aged {ages} are Wayners from {origin} travelling to 
    {destination} between {start_date} arriving at {flight_outward_arrival_time} 
    and {end_date} departing at {flight_return_departure_time} from {destination}'s airport. 
    The travellers are staying at {hotel_name}, which is already booked for {names}. 
    Is breakfast included in the hotel? {breakfast_included}. The flights are also booked:
    {flight_data}. 
    Only hotel and flights are booked, any other activity is not booked yet.
    IT IS ESPECIALLY IMPORTANT TO INCLUDE DIRECTIONS TO THE HOTEL FROM THE AIRPORT AND FROM THE AIRPORT TO THE HOTEL.
    DO NOT INVENT ANY INDICATION.
    MAKE SURE THE TRAVELLER GETS TO THE AIRPORT 2 HOURS BEFORE THE FLIGHT DEPARTS. 
  expected_output: >
    Fully developed, complete, detailed, and geographically optimized itinerary with distances and transportation options (including times and prices when appropriate) between activities, including ONLY PUBLIC TRANSPORTATION, NEVER INCLUDING TAXI OR PRIVATE SHUTTLES.
    IT MUST CONTAIN RESEARCHED PUBLIC TRANSPORTATION OPTIONS BETWEEN EACH AND EVERY LOCATION OF THE ITINERARY. THE TRAVELLER MUST GET TO THE AIRPORT 2 HOURS BEFORE THE FLIGHT DEPARTS. 
    It must contain the following structure WITH ALL THE PREVIOUS INFORMATION:
    - Greeting and presentation of the recommended itinerary.
    - Hotel Information (stars, location, reviews...).
    - Flight Information.
    - Specific weather forecast day by day.
    - Extensive, complete itinerary, with ALL THE DETAILS FROM THE PREVIOUS ITINERARY PLUS TRANSPORTATION OPTIONS.
    - Fun facts and top tips, such as what to book in advance.
    - Olga Informal Signature.

itinerary_translation_and_writing:
  description: >
    Develop a message in WhatsApp format in {origin}'s language keeping all the information and the complete, detailed day-by-day itinerary prepared to be sent to the user. Consider the following indications:
    
    {num_travelers} people named {names} aged {ages} are Wayners from {origin} travelling to 
    {destination} between {start_date} arriving at {flight_outward_arrival_time} 
    and {end_date} departing at {flight_return_departure_time} from {destination}'s airport. 
    The travellers are staying at {hotel_name}, which is already booked for {names}. 
    Is breakfast included in the hotel? {breakfast_included}. The flights are also booked:
    {flight_data}. 
    Only hotel and flights are booked, any other activity is not booked yet.
    DO NOT INVENT ANY INFORMATION.
  expected_output: >
    A well-structured and extremely informative Whatsapp text-message in text format (NOT MARKDOWN) READY TO BE SENT DIRECTLY TO {names} (wayners) in their country's national language. IT MUST BE IN {origin}'s country's national language.
    It must include the FULL COMPLETE DETAILED RECOMMENDED ITINERARY DAY BY DAY WITH ALL THE DAYS ACTIVITIES AND TRANSPORT OPTIONS developed up to now (including prices and all useful data points) addressing the travellers as "Wayners".
    Make sure you frame it as a RECOMMENDED itinerary and consider that THE FULL OUTPUT WILL BE RECEIVED BY {names}, so JUST PROVIDE THE TEXT TO BE SENT TO THE TRAVELLERS. NEVER ASSUME ACTIVITES (EXCEPT HOTELS AND FLIGHTS) ARE ALREADY BOOKED, THEY ARE JUST RECOMMENDATIONS. Sign as Olga from Waynabox.
    It must have the FULL COMPLETE following structure and the full text must be in {origin}'s country national official language:
    - Greeting and presentation of the recommended itinerary.
    - Hotel Information (stars, location, reviews...).
    - Flight Information.
    - Specific weather forecast day by day.
    - Extensive, complete itinerary, with ALL THE DETAILS FROM THE PREVIOUS ITINERARY.
    - Fun facts and top tips, such as what to book in advance.
    - Olga Informal Signature.

PR_adaptation:
  description: >
    Improve the message to make it extremely beautiful and engaging while keeping all the details.
    Make sure it contains A LOT of emojis and textual techniques to make it extremely engaging and appealing.
    Ensure the traveller understands that it is a recommended itinerary and none of the mentioned restaurants or activities are booked, they are just recommendations.
    IMPORTANT: THIS IS A MUST, DO NOT USE "#" AND MAKE THE FORMAT VERY CLEAN AND APPEALING.
    IMPORTANT: USE BOLD FOR THE TITLE OF EACH SECTION TO MAKE IT EASIER TO FOLLOW.
    DIVIDE THE DAYS STARTING EACH DAY WITH **DAY 1**, **DAY 2**, **DAY 3**. USE BOLD THERE AND IN THE HOURS.
    DO NOT USE BOLD ANYWHERE ELSE, ONLY IN THE TITLES OF SECTIONS, DAYS AND HOURS. ABSOLUTELY NOWHERE ELSE.
    IMPORTANT: USE BULLET POINTS.
    IMPORTANT: DO NOT USE MARKDOWN, MAKE IT VERY EASY TO FOLLOW.
    IMPORTANT: YOU MUST ABSOLUTELY ALWAYS INCLUDE AT LEAST 2 CIVITATIS LINKS WITH THE ACTIVITIES.
  expected_output: >
    A Whatsapp message with the same information and level of detail but PR-optimized for engagement and aesthetics.
    It must be really appealing, eye-catching and contain A TON OF EMOJIS.
    It must seem written by a human expert.
    It must have the FULL COMPLETE following structure and the full text must be in {origin}'s country national official language:
    - Greeting and presentation of the recommended itinerary.
    - Hotel Information (stars, location, reviews...).
    - Flight Information.
    - Specific weather forecast day by day. USE ACCUWEATHER TO ENSURE THE WEATHER IS CORRECT. 
    - Extensive, complete itinerary, with ALL THE DETAILS FROM THE PREVIOUS ITINERARY. CIVITATIS LINKS MUST BE INCLUDED.
    - Fun facts and top tips, such as what to book in advance.
    - Olga Informal Signature.
    IMPORTANT: BOLD MUST ONLY BE USED IN THE TITLES OF SECTIONS, TITLES OF DAYS AND THE SPECIFIC HOURS.
    IMPORTANT: IT MUST ALWAYS ALWAYS ALWAYS INCLUDE A DISCLAIMER (NOT IN BOLD) THAT SAYS THAT NONE OF THE MENTIONED RESTAURANTS OR ACTIVITIES ARE BOOKED, THEY ARE JUST RECOMMENDATIONS.
